name: portfolio
description: "@Dev-Salem's Portfolio"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  mesh: ^0.4.2
  flutter_animate: ^4.5.2
  video_player: ^2.9.2
  responsive_builder: ^0.7.1
  url_launcher: ^6.3.1
  google_fonts: ^5.1.0
  flutter_launcher_icons: ^0.14.3
  cached_network_image: ^3.4.1
  flutter_infinite_marquee: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/main-icon.png"
  web:
    generate: true
    image_path: "assets/main-icon.png"
    background_color: "#D9D9D9"